"""empty message

Revision ID: 052d03669d4f
Revises: 6cc5d45a2f91
Create Date: 2025-11-05 12:55:49.790335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052d03669d4f'
down_revision = '6cc5d45a2f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('pattern', sa.String(length=50), nullable=False),
    sa.Column('sleeve_length', sa.Float(), nullable=False),
    sa.Column('neckline', sa.String(length=50), nullable=False),
    sa.Column('train_length', sa.Float(), nullable=False),
    sa.Column('texture', sa.String(length=50), nullable=False),
    sa.Column('texture_intensity', sa.Float(), nullable=False),
    sa.Column('skirt_volume', sa.Float(), nullable=False),
    sa.Column('svg', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurement_unit', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_profiles', schema=None) as batch_op:
        batch_op.drop_column('measurement_unit')

    op.drop_table('designs')
    # ### end Alembic commands ###
