"""empty message

Revision ID: baf5e7e14ab3
Revises: 052d03669d4f
Create Date: 2025-11-10 14:19:23.021818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf5e7e14ab3'
down_revision = '052d03669d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('chest', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('waist', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hips', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shoulder_width', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('arm_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('inseam', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thigh', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('neck', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('calf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('wrist', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('patterns', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('necklines', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sleeves', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top_styles', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fabric_textures', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fabric_types', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_profiles', schema=None) as batch_op:
        batch_op.drop_column('fabric_types')
        batch_op.drop_column('fabric_textures')
        batch_op.drop_column('top_styles')
        batch_op.drop_column('sleeves')
        batch_op.drop_column('necklines')
        batch_op.drop_column('patterns')
        batch_op.drop_column('wrist')
        batch_op.drop_column('calf')
        batch_op.drop_column('neck')
        batch_op.drop_column('thigh')
        batch_op.drop_column('inseam')
        batch_op.drop_column('arm_length')
        batch_op.drop_column('shoulder_width')
        batch_op.drop_column('hips')
        batch_op.drop_column('waist')
        batch_op.drop_column('chest')
        batch_op.drop_column('weight')
        batch_op.drop_column('age')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
