"""empty message

Revision ID: eb70b03cf846
Revises: baf5e7e14ab3
Create Date: 2025-11-10 14:35:27.215464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb70b03cf846'
down_revision = 'baf5e7e14ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gown_designs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measurements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('customizations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gown_designs', schema=None) as batch_op:
        batch_op.drop_column('customizations')
        batch_op.drop_column('measurements')

    # ### end Alembic commands ###
